<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <!--viewport settings for responsive design-->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!--page description -->
    <meta name="description" content="Home Page for LeafByte Tech">
    <!--keywords for the page -->
    <meta name="keywords" content="HTML, LeafByte Tech, Technology, IT, Jobs, Apply, Apply for a Job, Application, Software, Developer, Engineer">
    <link rel="stylesheet" type="text/css" href="styles/styles.css">