<nav class="nav">
        <!--Applied <p> to group individual navigation links -->
        <!--Applied <a> to create clickable links to other pages and email-->
            <p class="menu"><a href="./index.php" class="CustomLink">HOME</a></p> 
            <p class="menu"><a href="./jobs.php" class="CustomLink">JOBS</a> </p> 
            <p class="menu"><a href="./apply.php" class="CustomLink">APPLY</a></p> 
            <p class="menu"><a href="./about.php" class="CustomLink">ABOUT</a></p> 
		<p class="menu"><a href="mailto:info@LeafByteTech.com.au" class="CustomLink">CONTACT</a></p> 
</nav>